version: "3.7"

services:
  database_chapter04:
    image: postgres
    container_name: database_chapter04
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: app_chapter04
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_chapter04
    depends_on: 
      - database_chapter04

volumes:
  pgdata:
    driver: local